# A string used to distinguish different Supabase projects on the same host.
project_id = "iqraa"

[api]
enabled = true
port = 54421
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54422
shadow_port = 54420
major_version = 15

[db.pooler]
enabled = false
port = 54429
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54423
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[local_smtp]
enabled = true
port = 54424

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.buckets.covers]
public = true
file_size_limit = "11MiB"
allowed_mime_types = ["image/jpeg", "image/png", "image/webp"]

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false

[analytics]
enabled = false
